### ISSUE TITLE
Client PUT, DELETE, POST methods don't work

### ISSUE THREAD

**Issue by antoniofruci** [ryanmurakami/node-storenvy#5]
You are using node http methods, that actually don't exist.

**Comment by ryanmurakami** [comment]
Yep, you're totally right. Wouldn't it be great it they did, though!

**Comment by antoniofruci** [comment]
I forked the repo and I am fixing it myself. I need something working quickly, so I am just fixing what I need, but it could be helpful to take a look, if you want.

**Comment by ryanmurakami** [comment]
Ah, sorry about that. Yeah, I pushed a fix to the develop branch but I want to test it more. It differs a little from what you did but I think it may work.

**Comment by antoniofruci** [comment]
I see. But if I may ask, why do you build the URL to pass to the .post method and then you parse it? Also, the token is set when the client is created, why do you pass it to the call function each time?

**Comment by ryanmurakami** [comment]
Hmm... it's just a holdover from the get, which just needs a url. I like the idea of being able to just say "post to this url" and let the post function figure out any https implementation. Also, you shouldn't need to pass the token after setting up the client. It's more of an optional parameter. I probably need to take another look at that though.

**Comment by ryanmurakami** [comment]
Fixed this. Everything should be working smoothly now.
